### ISSUE TITLE
DevEco Studio无法安装3.99.2

### ISSUE THREAD

**Issue by miniscale** [xuhuanzy/TranslationPlugin-New#2]
### 需求/建议描述

![1](https://github.com/user-attachments/assets/ab190e96-a600-45b4-ae02-c61e3b5264f1)

### 建议的解决方案

@xuhuanzy 麻烦可以适配一下吗

**Comment by xuhuanzy** [comment]
233的话原版应该能用吧？确定原版文档翻译无效？

**Comment by miniscale** [comment]
> 233的话原版应该能用吧？确定原版文档翻译无效？

原版文档翻译无效

**Comment by miniscale** [comment]
![PixPin_2024-11-27_18-53-22](https://github.com/user-attachments/assets/6894e835-6f0b-406f-b089-21e179d4fe27)
这个代码问题能翻译吗

**Comment by xuhuanzy** [comment]
> 这个代码问题能翻译吗

不能.

> 原版文档翻译无效

压缩包里的`TranslationPlugin-3.99.2.jar` -> META-INF -> `plugin.xml` 
![image](https://github.com/user-attachments/assets/4f4e9d7b-4a4a-4934-950b-5da21b2a8871)
`since-build`的目标改为233看看

**Comment by miniscale** [comment]
> > 这个代码问题能翻译吗
> 
> 不能.
> 
> > 原版文档翻译无效
> 
> 压缩包里的`TranslationPlugin-3.99.2.jar` -> META-INF -> `plugin.xml` 
> ![image](https://github.com/user-attachments/assets/4f4e9d7b-4a4a-4934-950b-5da21b2a8871)
> `since-build`的目标改为233看看

改版本后可以安装
